title: "My Data ML Project Blog"
description: "A blog about machine learning and statistics"
theme: minima  # Or any GitHub-supported theme
permalink : pretty
# Correct baseurl for loading images properly
baseurl: "/test-jekyll"  # Change this from "/data-ml-project" to ""

url: "https://zenahmad06.github.io"
include:
  -assets

# Define where static assets (like images) are stored
defaults:
  - scope:
      path: "assets/images-desc"
    values:
      image: true

defaults:
  - scope:
      path: "assets/image-bin"
    values:
      image: true
defaults:
  - scope:
      path: "assets/image-cnn-rps"
    values:
      image: true
defaults:
  - scope:
      path: "assets/image-mumbai"
    values:
      image: true
defaults:
  - scope:
      path: "assets/image-scrap"
    values:
      image: true
defaults:
  - scope:
      path: "assets/image-feature"
    values:
      image: true
defaults:
  - scope:
      path: "assets/image-loanapproval"
    values:
      image: true
defaults:
  - scope:
      path: "assets/images-insurances"
    values:
      image: true


# Ensure Jekyll processes images correctly
plugins:
  - jekyll-feed
  - jekyll-seo-tag
